import { useEffect,useRef,useState } from "react";
import { useNavigate } from "react-router-dom";
import { ChevronLeft,Search,Users } from "lucide-react";
import { beginOperation,finishOperation } from "@/api/idempotency";
import { Money,ServerPagination } from "@/shared/components";
import PageHeader from "@/shared/components/PageHeader/PageHeader";
import CustomerForm from "../components/CustomerForm";
import { customersApi } from "../api/customers.api";
import "../styles/CustomersPage.css";
const msg=e=>e?.response?.data?.error?.messageAr||e?.response?.data?.message||e.message;
export default function CustomersPage(){const nav=useNavigate(),scope=useRef("customer:create");const[page,setPage]=useState(1),[search,setSearch]=useState(""),[data,setData]=useState({customers:[],pageMeta:{}}),[loading,setLoading]=useState(true),[error,setError]=useState(""),[saving,setSaving]=useState(false);const load=async()=>{setLoading(true);try{setData(await customersApi.screen({page,limit:10,search:search.trim()||undefined}));setError("");}catch(e){setError(msg(e));}finally{setLoading(false);}};useEffect(()=>{const timer=setTimeout(load,250);return()=>clearTimeout(timer);},[page,search]);const create=async payload=>{setSaving(true);try{await customersApi.create(payload,beginOperation(scope.current));finishOperation(scope.current);await load();}catch(e){setError(msg(e));throw e;}finally{setSaving(false);}};const rows=data.customers||[];return <div className="customers-page"><PageHeader title="إدارة العملاء" breadcrumbs={["الرئيسية","العملاء"]}/><div className="customers-form-section"><h3>تسجيل عميل جديد</h3><CustomerForm onSubmit={create} busy={saving}/></div><div className="customers-list-section"><div className="customers-list-head"><h3><Users size={18}/> العملاء ({data.summary?.total??0})</h3><div className="customers-search"><Search size={16}/><input value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}} placeholder="بحث بالاسم أو الهاتف"/></div></div>{error&&<p role="alert" className="delegates-error">{error}</p>}{loading?<p>جاري التحميل...</p>:<div className="customers-table-wrap"><table className="customers-table"><thead><tr><th>الاسم</th><th>الهاتف</th><th>العنوان</th><th>الحالة</th><th>الطلبات</th><th>المكتملة</th><th>إجمالي المشتريات</th><th className="ct-actions-head">فتح</th></tr></thead><tbody>{rows.length?rows.map(c=><tr key={c.id} onClick={()=>nav(`/admin/customers/${c.id}`)}><td data-label="الاسم" className="ct-name">{c.name||"—"}</td><td data-label="الهاتف" className="ct-phone">{c.phone||"—"}</td><td data-label="العنوان" className="ct-address" title={c.address||undefined}>{c.address||"—"}</td><td data-label="الحالة"><span className={`customer-status customer-status--${String(c.status||"").toLowerCase()}`}>{c.status||"—"}</span></td><td data-label="الطلبات" className="ct-num">{c.orderCount??0}</td><td data-label="المكتملة" className="ct-num">{c.completedOrderCount??0}</td><td data-label="إجمالي المشتريات" className="ct-total"><Money value={c.lifetimeValue}/></td><td className="ct-actions-cell"><button type="button" className="customer-open-btn" aria-label={`فتح صفحة ${c.name||""}`} title="فتح" onClick={(event)=>{event.stopPropagation();nav(`/admin/customers/${c.id}`);}}><ChevronLeft size={16}/></button></td></tr>):<tr className="customers-empty-row"><td colSpan="8">لا يوجد عملاء مطابقون للبحث.</td></tr>}</tbody></table></div>}<ServerPagination meta={data.pageMeta} disabled={loading} label="عميل" onPageChange={setPage}/></div></div>}
